# Generated by Django 6.1.1 on 2026-09-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contactform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='costumer_email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='contactform',
            old_name='costumer_name',
            new_name='customer_name',
        ),
    ]
